# Site settings
title: Anthony Erlinger
email: aerlinger@examplt.com
description: "Portfolio site of a developer, data hacker, makeshift designer, and science nut."
baseurl: "/"
url: "http://aerlinger.com"

# Build settings
markdown: kramdown
permalink: pretty

collections:
  - projects
