# Site settings
title: Anthony Erlinger
email: aerlinger@examplt.com
description: "Portfolio site of a developer and technology enthusiast."
baseurl: ""
url: "http://aerlinger.com"

# Build settings
markdown: kramdown
permalink: pretty
