# Site settings
title: Anthony Erlinger
email: aerlinger@examplt.com
description: "Portfolio site of a developer, data hacker, and science junkie."
baseurl: "/"
url: "http://aerlinger.com"

# Build settings
markdown: kramdown
permalink: pretty
